package com.itsol.smartweb.model;
// Generated Mar 1, 2019 4:33:38 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblCandidate generated by hbm2java
 */
@Entity
@Table(name = "tbl_candidate", catalog = "smart_web")
public class TblCandidate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int candidateId;
	private TblUser tblUser;
	private TblJob tblJob;
	private String candidateFirstname;
	private String candidatelLastname;
	private Date candidateBirth;
	private String candidateEmail;
	private String candidateMobile;
	private String candidateCvfile;
	private String candidateContent;

	public TblCandidate() {
	}

	public TblCandidate(int candidateId, TblJob tblJob) {
		this.candidateId = candidateId;
		this.tblJob = tblJob;
	}

	public TblCandidate(int candidateId, TblUser tblUser, TblJob tblJob, String candidateFirstname,
			String candidatelLastname, Date candidateBirth, String candidateEmail, String candidateMobile,
			String candidateCvfile, String candidateContent) {
		this.candidateId = candidateId;
		this.tblUser = tblUser;
		this.tblJob = tblJob;
		this.candidateFirstname = candidateFirstname;
		this.candidatelLastname = candidatelLastname;
		this.candidateBirth = candidateBirth;
		this.candidateEmail = candidateEmail;
		this.candidateMobile = candidateMobile;
		this.candidateCvfile = candidateCvfile;
		this.candidateContent = candidateContent;
	}

	@Id

	@Column(name = "candidate_id", unique = true, nullable = false)
	public int getCandidateId() {
		return this.candidateId;
	}

	public void setCandidateId(int candidateId) {
		this.candidateId = candidateId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tbl_user_user_id")
	public TblUser getTblUser() {
		return this.tblUser;
	}

	public void setTblUser(TblUser tblUser) {
		this.tblUser = tblUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tbl_job_job_id", nullable = false)
	public TblJob getTblJob() {
		return this.tblJob;
	}

	public void setTblJob(TblJob tblJob) {
		this.tblJob = tblJob;
	}

	@Column(name = "candidate_firstname", length = 45)
	public String getCandidateFirstname() {
		return this.candidateFirstname;
	}

	public void setCandidateFirstname(String candidateFirstname) {
		this.candidateFirstname = candidateFirstname;
	}

	@Column(name = "candidatel_lastname", length = 45)
	public String getCandidatelLastname() {
		return this.candidatelLastname;
	}

	public void setCandidatelLastname(String candidatelLastname) {
		this.candidatelLastname = candidatelLastname;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "candidate_birth", length = 10)
	public Date getCandidateBirth() {
		return this.candidateBirth;
	}

	public void setCandidateBirth(Date candidateBirth) {
		this.candidateBirth = candidateBirth;
	}

	@Column(name = "candidate_email", length = 45)
	public String getCandidateEmail() {
		return this.candidateEmail;
	}

	public void setCandidateEmail(String candidateEmail) {
		this.candidateEmail = candidateEmail;
	}

	@Column(name = "candidate_mobile", length = 45)
	public String getCandidateMobile() {
		return this.candidateMobile;
	}

	public void setCandidateMobile(String candidateMobile) {
		this.candidateMobile = candidateMobile;
	}

	@Column(name = "candidate_cvfile", length = 65535)
	public String getCandidateCvfile() {
		return this.candidateCvfile;
	}

	public void setCandidateCvfile(String candidateCvfile) {
		this.candidateCvfile = candidateCvfile;
	}

	@Column(name = "candidate_content", length = 65535)
	public String getCandidateContent() {
		return this.candidateContent;
	}

	public void setCandidateContent(String candidateContent) {
		this.candidateContent = candidateContent;
	}

}
