package com.itsol.smartweb.model;
// Generated Mar 1, 2019 4:33:38 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TblJob generated by hbm2java
 */
@Entity
@Table(name = "tbl_job", catalog = "smart_web")
public class TblJob implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer jobId;
	private String jobAvatar;
	private String jobTitle;
	private String jobCity;
	private Double jobSalary;
	private String jobNote;
	private Set<TblCandidate> tblCandidates = new HashSet<TblCandidate>(0);

	public TblJob() {
	}

	public TblJob(String jobAvatar, String jobTitle, String jobCity, Double jobSalary, String jobNote,
			Set<TblCandidate> tblCandidates) {
		this.jobAvatar = jobAvatar;
		this.jobTitle = jobTitle;
		this.jobCity = jobCity;
		this.jobSalary = jobSalary;
		this.jobNote = jobNote;
		this.tblCandidates = tblCandidates;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "job_id", unique = true, nullable = false)
	public Integer getJobId() {
		return this.jobId;
	}

	public void setJobId(Integer jobId) {
		this.jobId = jobId;
	}

	@Column(name = "job_avatar", length = 65535)
	public String getJobAvatar() {
		return this.jobAvatar;
	}

	public void setJobAvatar(String jobAvatar) {
		this.jobAvatar = jobAvatar;
	}

	@Column(name = "job_title", length = 45)
	public String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	@Column(name = "job_city", length = 45)
	public String getJobCity() {
		return this.jobCity;
	}

	public void setJobCity(String jobCity) {
		this.jobCity = jobCity;
	}

	@Column(name = "job_salary", precision = 22, scale = 0)
	public Double getJobSalary() {
		return this.jobSalary;
	}

	public void setJobSalary(Double jobSalary) {
		this.jobSalary = jobSalary;
	}

	@Column(name = "job_note", length = 65535)
	public String getJobNote() {
		return this.jobNote;
	}

	public void setJobNote(String jobNote) {
		this.jobNote = jobNote;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblJob")
	@JsonIgnore
	public Set<TblCandidate> getTblCandidates() {
		return this.tblCandidates;
	}

	public void setTblCandidates(Set<TblCandidate> tblCandidates) {
		this.tblCandidates = tblCandidates;
	}

}
