package com.itsol.smartweb.model;
// Generated Mar 1, 2019 4:33:38 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblNewsId generated by hbm2java
 */
@Embeddable
public class TblNewsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int newsId;
	private int tblCategoriesId;

	public TblNewsId() {
	}

	public TblNewsId(int newsId, int tblCategoriesId) {
		this.newsId = newsId;
		this.tblCategoriesId = tblCategoriesId;
	}

	@Column(name = "news_id", nullable = false)
	public int getNewsId() {
		return this.newsId;
	}

	public void setNewsId(int newsId) {
		this.newsId = newsId;
	}

	@Column(name = "tbl_categories_id", nullable = false)
	public int getTblCategoriesId() {
		return this.tblCategoriesId;
	}

	public void setTblCategoriesId(int tblCategoriesId) {
		this.tblCategoriesId = tblCategoriesId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblNewsId))
			return false;
		TblNewsId castOther = (TblNewsId) other;

		return (this.getNewsId() == castOther.getNewsId())
				&& (this.getTblCategoriesId() == castOther.getTblCategoriesId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNewsId();
		result = 37 * result + this.getTblCategoriesId();
		return result;
	}

}
