package com.itsol.smartweb.model;
// Generated Mar 1, 2019 4:33:38 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TblUser generated by hbm2java
 */
@Entity
@Table(name = "tbl_user", catalog = "smart_web", uniqueConstraints = @UniqueConstraint(columnNames = "user_email"))
public class TblUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer userId;
	private String userEmail;
	private String userPassword;
	private String userFirstname;
	private String userLastname;
	private String userFullname;
	private String userMobile;
	private int userRoles;
	private byte userStatus;
	private String userNotes;
	private String userAvatar;
	private String userSkype;
	private String userFacebook;
	private String userAddress;
	private String userEducation;
	private String userSchool;
	private String userFaculty;
	private Date userYearfinish;
	private String userSkill;
	private String userExperience;
	private String userHistory;
	private Set<TblNews> tblNewses = new HashSet<TblNews>(0);
	private Set<TblCandidate> tblCandidates = new HashSet<TblCandidate>(0);

	public TblUser() {
	}

	public TblUser(String userEmail, String userPassword, String userFirstname, String userLastname,
			String userFullname, String userMobile, int userRoles, byte userStatus, String userAddress) {
		this.userEmail = userEmail;
		this.userPassword = userPassword;
		this.userFirstname = userFirstname;
		this.userLastname = userLastname;
		this.userFullname = userFullname;
		this.userMobile = userMobile;
		this.userRoles = userRoles;
		this.userStatus = userStatus;
		this.userAddress = userAddress;
	}

	public TblUser(String userEmail, String userPassword, String userFirstname, String userLastname,
			String userFullname, String userMobile, int userRoles, byte userStatus, String userNotes, String userAvatar,
			String userSkype, String userFacebook, String userAddress, String userEducation, String userSchool,
			String userFaculty, Date userYearfinish, String userSkill, String userExperience, String userHistory,
			Set<TblNews> tblNewses, Set<TblCandidate> tblCandidates) {
		this.userEmail = userEmail;
		this.userPassword = userPassword;
		this.userFirstname = userFirstname;
		this.userLastname = userLastname;
		this.userFullname = userFullname;
		this.userMobile = userMobile;
		this.userRoles = userRoles;
		this.userStatus = userStatus;
		this.userNotes = userNotes;
		this.userAvatar = userAvatar;
		this.userSkype = userSkype;
		this.userFacebook = userFacebook;
		this.userAddress = userAddress;
		this.userEducation = userEducation;
		this.userSchool = userSchool;
		this.userFaculty = userFaculty;
		this.userYearfinish = userYearfinish;
		this.userSkill = userSkill;
		this.userExperience = userExperience;
		this.userHistory = userHistory;
		this.tblNewses = tblNewses;
		this.tblCandidates = tblCandidates;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "user_email", unique = true, nullable = false, length = 100)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "user_password", nullable = false, length = 45)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "user_firstname", nullable = false, length = 45)
	public String getUserFirstname() {
		return this.userFirstname;
	}

	public void setUserFirstname(String userFirstname) {
		this.userFirstname = userFirstname;
	}

	@Column(name = "user_lastname", nullable = false, length = 45)
	public String getUserLastname() {
		return this.userLastname;
	}

	public void setUserLastname(String userLastname) {
		this.userLastname = userLastname;
	}

	@Column(name = "user_fullname", nullable = false, length = 45)
	public String getUserFullname() {
		return this.userFullname;
	}

	public void setUserFullname(String userFullname) {
		this.userFullname = userFullname;
	}

	@Column(name = "user_mobile", nullable = false, length = 45)
	public String getUserMobile() {
		return this.userMobile;
	}

	public void setUserMobile(String userMobile) {
		this.userMobile = userMobile;
	}

	@Column(name = "user_roles", nullable = false)
	public int getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(int userRoles) {
		this.userRoles = userRoles;
	}

	@Column(name = "user_status", nullable = false)
	public byte getUserStatus() {
		return this.userStatus;
	}

	public void setUserStatus(byte userStatus) {
		this.userStatus = userStatus;
	}

	@Column(name = "user_notes", length = 65535)
	public String getUserNotes() {
		return this.userNotes;
	}

	public void setUserNotes(String userNotes) {
		this.userNotes = userNotes;
	}

	@Column(name = "user_avatar", length = 65535)
	public String getUserAvatar() {
		return this.userAvatar;
	}

	public void setUserAvatar(String userAvatar) {
		this.userAvatar = userAvatar;
	}

	@Column(name = "user_skype", length = 65535)
	public String getUserSkype() {
		return this.userSkype;
	}

	public void setUserSkype(String userSkype) {
		this.userSkype = userSkype;
	}

	@Column(name = "user_facebook", length = 65535)
	public String getUserFacebook() {
		return this.userFacebook;
	}

	public void setUserFacebook(String userFacebook) {
		this.userFacebook = userFacebook;
	}

	@Column(name = "user_address", nullable = false, length = 45)
	public String getUserAddress() {
		return this.userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	@Column(name = "user_education", length = 45)
	public String getUserEducation() {
		return this.userEducation;
	}

	public void setUserEducation(String userEducation) {
		this.userEducation = userEducation;
	}

	@Column(name = "user_school", length = 45)
	public String getUserSchool() {
		return this.userSchool;
	}

	public void setUserSchool(String userSchool) {
		this.userSchool = userSchool;
	}

	@Column(name = "user_faculty", length = 45)
	public String getUserFaculty() {
		return this.userFaculty;
	}

	public void setUserFaculty(String userFaculty) {
		this.userFaculty = userFaculty;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "user_yearfinish", length = 10)
	public Date getUserYearfinish() {
		return this.userYearfinish;
	}

	public void setUserYearfinish(Date userYearfinish) {
		this.userYearfinish = userYearfinish;
	}

	@Column(name = "user_skill", length = 45)
	public String getUserSkill() {
		return this.userSkill;
	}

	public void setUserSkill(String userSkill) {
		this.userSkill = userSkill;
	}

	@Column(name = "user_experience", length = 65535)
	public String getUserExperience() {
		return this.userExperience;
	}

	public void setUserExperience(String userExperience) {
		this.userExperience = userExperience;
	}

	@Column(name = "user_history", length = 65535)
	public String getUserHistory() {
		return this.userHistory;
	}

	public void setUserHistory(String userHistory) {
		this.userHistory = userHistory;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblUser")
	public Set<TblNews> getTblNewses() {
		return this.tblNewses;
	}

	public void setTblNewses(Set<TblNews> tblNewses) {
		this.tblNewses = tblNewses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblUser")
	public Set<TblCandidate> getTblCandidates() {
		return this.tblCandidates;
	}

	public void setTblCandidates(Set<TblCandidate> tblCandidates) {
		this.tblCandidates = tblCandidates;
	}

}
